name: CI

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/pspdev/pspdev:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk add make git bash cmake

    # To be removed once the fjtrujy fork is part of PSPDEV
    - name: Install fjtrujy SDL2 fork
      run: |
        git clone -b pspRefactorRender https://github.com/fjtrujy/SDL.git
        cd SDL
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake  -DCMAKE_INSTALL_PREFIX=$PSPDEV/psp \
          -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=OFF -DSDL_TESTS=OFF ..
        make -j $(getconf _NPROCESSORS_ONLN)
        make -j $(getconf _NPROCESSORS_ONLN) install
    

    - name: Compile project
      run: |
        mkdir build && cd build
        psp-cmake ..
        make

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: hello-${{ steps.slug.outputs.sha8 }}
        path: | 
          build/EBOOT.PBP
