name: CI

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/pspdev/pspdev:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk add make git bash cmake

    - name: Compile project
      run: |
        mkdir build && cd build
        psp-cmake ..
        make

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: hello-${{ steps.slug.outputs.sha8 }}
        path: | 
          build/EBOOT.PBP
          build/texture
          build/texture.prx
          build/grass.png

  execute:
    needs: [build]
    runs-on: ubuntu-latest
    container: ghcr.io/hrydgard/ppsspp:latest

    steps:
    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: hello-${{ steps.slug.outputs.sha8 }}
    
    - name: Execute ELF
      run: |
        PPSSPPHeadless --graphics=software --log --verbose $(pwd)/EBOOT.PBP

    - name: Check artifact
      run: ls -R .

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: hello-gmon-${{ steps.slug.outputs.sha8 }}
        path: | 
          gmon.out
          texture

  generate_report:
    needs: [execute]
    runs-on: ubuntu-latest
    container: ghcr.io/pspdev/psptoolchain:latest

    steps:
    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Download binaryartifact
      uses: actions/download-artifact@v4
      with:
        name: hello-gmon-${{ steps.slug.outputs.sha8 }}
  
    - name: Check artifact
      run: ls -R .
  
    - name: Generate report
      run: |
        psp-gprof -b texture gmon.out > report.txt
        cat report.txt