name: CI

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/pspdev/pspsdk:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk add make git bash
    

    - name: Compile project
      run: |
        make clean all

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: hello-${{ steps.slug.outputs.sha8 }}
        path: | 
          EBOOT.PBP

  execute:
    needs: [build]
    runs-on: ubuntu-latest
    container: ghcr.io/hrydgard/ppsspp:latest

    steps:
    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: hello-${{ steps.slug.outputs.sha8 }}
    
    - name: Check artifact
      run: ls -R .
    
    - name: Execute ELF
      run: |
        PPSSPPHeadless EBOOT.PBP --log
